source = ~/.config/hypr/mocha.conf
background {
    monitor =
    path = ~/Pictures/wallpapers/genshin_2.png
    color = rgba(25, 20, 20, 1.0)
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = $lavendar $sky 20deg
    check_color = $yellow $peach 80deg
    fail_color = $red $flamingo 140deg
    fail_text = Wrong Password

    font_color = $green
    fade_on_empty = false
    rounding = 15

    position = 0, -200
    halign = center
    valign = center
}

label {
    monitor = 
    text = $TIME12
    # text = cmd echo "$(date +"%H:%M")"
    color = $red
    font_size = 50
    font_family = JetBrainsMono Nerd Font

    position = 0, 0
    halign = center
    valign = top
}

label {
    monitor =
    text = Hi there :)
    color = rgb(253, 161, 21)
    font_size = 50
    font_family = Comic Sans MS Bold Italic

    position = 0, 0
    halign = center
    valign = center
}

label {
	monitor = 
	text = $USER
	color = rgb(220, 0, 150)
	font_size = 40
	# font_family = JetBrainsMono Nerd Font
    font_family = Z003 Medium Italic

	position = 0, -100
	halign = center
	valign = center
}
